[build-system]
requires = ["setuptools>=62.3.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
    "gpu_sim: marks tests as using the GPU simulation (deselect with '-m \"not gpu_sim\"')",
    "serial",
]

[dependency-groups]
dev = [
    "diffusers>=0.37.1",
    "gymnasium>=1.3.0",
    "mani-skill>=3.0.1",
    "mplib==0.1.1",
    "numpy<2.0.0",
    "sapien>=3.0.3",
    "tensorboard>=2.20.0",
    "torch>=2.11.0",
    "transforms3d>=0.4.2",
    "wandb>=0.26.1",
]
